# meta

title: "njerig.me"
display-title: "njerig"
url: "https://njerig.me"
enforce_ssl: njerig.me


# build

plugins:
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap
exclude: 
  - Gemfile
  - Gemfile.lock
  - vendor

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

# site vars

permalink: /:categories/:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
