# meta

title: "njerig.me"
display-title: "njerig"
description:
url: "https://njerig.me"
enforce_ssl: njerig.me


# build

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
plugins: [jekyll-sitemap, jekyll-admin]
exclude: [Gemfile, Gemfile.lock, vendor]


# site vars

permalink: none

collections:
  posts:
    output: true
    permalink: /blog/:title