# meta

title: "njerig.me"
display-title: "njerig"
url: "https://njerig.me"
enforce_ssl: njerig.me


# build

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
exclude: 
  - Gemfile
  - Gemfile.lock
  - vendor

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "space_after_headers", "footnotes", "underline"]

excerpt_separator: <!--more-->

# site vars

permalink: /:categories/:year/:month/:day/:title

defaults:
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"
