title: njeri gachoka | njerig.me
email: njerig@mit.edu
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: njerigachoka
github_username:  njerig

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

exclude: [vendor]

sass:
  sass-dir: _sass
